[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"      # => web/functions
  node_bundler = "esbuild"

# ---------- Security Headers (all routes)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), payment=(), camera=(self)"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' data: https:; frame-ancestors 'self'; base-uri 'self'"

# Old links → new flow
[[redirects]]
  from = "/welcome"
  to = "/guest"
  status = 301
  force = true


# ---------- Observability proxy (MORE SPECIFIC; must come before /api/*)
[[redirects]]
  from = "/api/obs/*"
  to = "/.netlify/functions/obs/:splat"
  status = 200

# ---------- API reverse proxy (generic)
[[redirects]]
  from = "/api/*"
  to = "https://api.vaiyu.app/:splat"
  status = 200
  force = true

# ---------- SPA fallback (deep links load index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ---------- Long-term caching for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------- Service worker: fetch latest
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
