[build]
  command = "npm run build"
  publish = "dist"

# ---------- Core Security Headers (all routes)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP baseline (extend if you enable analytics; see notes below)
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' data: https:; frame-ancestors 'self'; base-uri 'self'"

# ---------- API Reverse Proxy (keep if you want /api/* to hit backend)
[[redirects]]
  from = "/api/*"
  to = "https://api.vaiyu.app/:splat"
  status = 200
  force = true

# ---------- SPA Fallback (deep links like /owner load index.html)
[[redirects]]
  from = "/**"
  to = "/index.html"
  status = 200

# ---------- Long-term caching for static assets (Vite outputs /assets/*)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
